# Generated by Django 5.1.5 on 2025-01-27 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_user_birthday_alter_user_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='The phone number is not valid. The phone number must start with 09 and contain 11 digits.', regex='^(09)\\d{9}$')], verbose_name='شماره تلفن'),
        ),
    ]
