# Generated by Django 5.1.5 on 2025-01-27 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('completed', models.BooleanField(default=False, verbose_name='تکمیل شده/نشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تعریف تسک')),
                ('updated_at', models.DateTimeField(verbose_name='تاریخ ویرایش تسک')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
